### ISSUE TITLE
Download stopping out of nowhere

### ISSUE THREAD

**Issue by LameProgrammer** [NobilityDeviant/ZenDownloader#21]
For some reason, it only downloads from 1-6 episodes and then the download stops out of nowhere

![{B5302F91-E474-4E51-B83C-81D99033D10C}](https://github.com/user-attachments/assets/b52efe50-cfe3-46e8-9264-c713276a535c)
![{2F8B5EE9-34E1-4ECF-8AE6-07ACD611772F}](https://github.com/user-attachments/assets/a3b2b36a-81b0-46bf-aac7-e48f05a644c7)

**Comment by ZetsApocNow** [comment]
same my console shows this if it helps
```
SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
Dec 27, 2024 3:23:19 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
Dec 27, 2024 3:23:19 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
Stacktrace for [S] [Captain N: The Game Master Season 1 Episode 2 Howﾁfs Bayou] Failed to create video file. Retrying...:
java.io.IOException: The system cannot find the path specified
at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
at java.base/java.io.File.createNewFile(Unknown Source)
at nobility.downloader.core.scraper.video_download.VideoDownloadHandler$run$2.invokeSuspend(VideoDownloadHandler.kt:98)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
Dec 27, 2024 3:32:25 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
                
              Dec 27, 2024 3:32:25 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
                
              Dec 27, 2024 4:25:14 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
Dec 27, 2024 4:25:15 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
```

**Comment by NobilityDeviant** [comment]
> same my console shows this if it helps
> 
> ```
> SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
> Dec 27, 2024 3:23:19 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
> WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
> Dec 27, 2024 3:23:19 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
> WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
> Stacktrace for [S] [Captain N: The Game Master Season 1 Episode 2 Howﾁfs Bayou] Failed to create video file. Retrying...:
> java.io.IOException: The system cannot find the path specified
> at java.base/java.io.WinNTFileSystem.createFileExclusively(Native Method)
> at java.base/java.io.File.createNewFile(Unknown Source)
> at nobility.downloader.core.scraper.video_download.VideoDownloadHandler$run$2.invokeSuspend(VideoDownloadHandler.kt:98)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:266)
> at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
> at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
> at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
> at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
> at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
> at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
> Dec 27, 2024 3:32:25 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
> WARNING: Connection reset
> java.net.SocketException: Connection reset
> at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
> at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source)
> at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
> at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
> at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source)
> at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
> at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
> at java.base/java.util.ArrayList.forEach(Unknown Source)
> at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
>                 
>               Dec 27, 2024 3:32:25 AM org.openqa.selenium.remote.http.WebSocket$Listener onError
> WARNING: Connection reset
> java.net.SocketException: Connection reset
> at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
> at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source)
> at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
> at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
> at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source)
> at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source)
> at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
> at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
> at java.base/java.util.ArrayList.forEach(Unknown Source)
> at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
>                 
>               Dec 27, 2024 4:25:14 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
> WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
> Dec 27, 2024 4:25:15 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
> WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
> ```

That is the most helpful error i've seen in a long time. I really need to update the logs 
Thank you I think i know what the issue is and why everyone's downloads have been stopping now.

**Comment by NobilityDeviant** [comment]
Ok so my earlier comment was wrong. That wasn't the reason it was stopping and honestly I have no idea why.
I haven't experienced this issue before, but I did make a lot of general improvements in [1.0.7](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.7)

Let me know if it helped.

**Comment by LameProgrammer** [comment]
I still have the same issue, here is the error console:
[Error Console.txt](https://github.com/user-attachments/files/18391247/Error.Console.txt)

**Comment by LameProgrammer** [comment]
> Ok so my earlier comment was wrong. That wasn't the reason it was stopping and honestly I have no idea why. I haven't experienced this issue before, but I did make a lot of general improvements in [1.0.7](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.7)
> 
> Let me know if it helped.

I still have the same issue, here is the error console:
[Error Console.txt](https://github.com/user-attachments/files/18391247/Error.Console.txt)

**Comment by NobilityDeviant** [comment]
Ok I believe i have finally fixed this one in 1.1.1 as well.
