### ISSUE TITLE
Various issues I have encountered while using the program

### ISSUE THREAD

**Issue by Neztic83** [NobilityDeviant/ZenDownloader#22]
This is my very first time writing an issue, I made this account specifically for this. 

This is a great downloader so far, and the only way to get past their little paywall.. However, it is rather buggy. I've been taking the approach of downloading all the shows one by one alphabetically for the sake of personal storage, and have encountered various bugs during my fiddling.

1. Can't queue downloads for more than three episodes at a time
![Screenshot_3](https://github.com/user-attachments/assets/cad16f36-b8ac-4211-bb8c-ad8d02899aa0)
At the fourth episode in the queue, it will crap out and not actually download anything. If left idle for a while, it will eventually cancel the process on it's own, with the "downloaded" video file in the folder, but entirely empty. There have been blue moon occasions where i'm able to queue an entire series successfully.
I'm using the current version, the last version would let me queue a lot more episodes successfully, maybe about 10 before I had to intervene? It's never not done this where it craps out though.

2. Download history is never truly gone
You can clear it from the top corner yeah, but it's never truly gone. A few resets of the program and your full history is back.

3. M3u8 shows do not work at all
![Screenshot_4](https://github.com/user-attachments/assets/9bef541e-3315-40ac-90f1-54f905eaaa39)

4. UI doesn't work at all on certain shows
![Screenshot_5](https://github.com/user-attachments/assets/07156afd-776d-4398-93ed-dc6029dd772f)
The only option that works regarding selection is the select all button. Downloading does seem to work, it's just that the UI for episode selection does not.

5. Program can take forever to actually close after a download session
It will often hang for minutes on end, there are times when I have to use task manager on it.

Successful download session Error Console output on my end:

SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
Dec 27, 2024 6:57:13 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131

Error Console output for issue 1:

SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
Dec 27, 2024 7:11:57 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131
Dec 27, 2024 7:24:26 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
                
              

Error Console output for issue 2:

SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
Dec 27, 2024 7:29:21 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 131, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 131

Error Console output for issue 4 is super long, I can't paste it due to the character limit. I hope this info helps you.

**Comment by NobilityDeviant** [comment]
I appreciate you signing up to submit such a detailed issue. Thank you very much.

1.  The queue issue has been noted and I am working on that.
2. I didn't notice this before and it was an easy fix.
3. I have no idea what's wrong, but I'll check that specific series and see what I can find.
4. The buttons do all work in the latest version. The checkbox are what you need to select even on the series row.
5. The program takes forever because it needs to clean all the resources. This is needed because your pc will just have all these chrome processes left open which isn't good. I will see if I can speed this up and maybe I'll add a little closing message as well.

Back to 4:

<img width="960" alt="selection" src="https://github.com/user-attachments/assets/261e01f7-40ae-47bf-bca4-dd0381895117" />

See the series rows are collapsable meaning that you have to click them to open/close them.
The checkbox on the series row also selects everything in that row and checkboxes next to every episode selects that particular episode. You can also just click on an episode inside the series row to select it.

However I do believe the series row checkbox is way too small. I have changed it to a more details button for the next update.

**Comment by Neztic83** [comment]
I see, thank you for the explanation for a lot of this. 

Though, about 4., it's not that i'm missing the dropdown rows when clicking, they worked for every other show but this one, and I think I encountered another show that did it but don't remember which (I only went through the entirety of the # list for all five site categories before giving up.). I couldn't use the dropdowns, I couldn't select all for a particular season, nothing. The only option that worked on my end was the select all button. Just from opening the episode selection window, it gives an extremely long console error, it was too long for me to paste. It may have been repeating the error every frame?

And for 3, it doesn't just apply to this particular show, but seemingly all shows that use m3u8, that i've tried at least.

**Comment by Neztic83** [comment]
[Error Log.txt](https://github.com/user-attachments/files/18269864/Error.Log.txt)
I realized I could just upload the error log to 4 as a txt file, this is what I get when I access it's download list.

**Comment by NobilityDeviant** [comment]
> [Error Log.txt](https://github.com/user-attachments/files/18269864/Error.Log.txt) I realized I could just upload the error log to 4 as a txt file, this is what I get when I access it's download list.

Thank you! I believe I have fixed this. Update will be coming in a couple of days

**Comment by NobilityDeviant** [comment]
I have pushed the update. [1.0.7](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.7)

This should address everything besides m3u8 downloading.
If all is well, I will close this issue and create my own for m3u8.

**Comment by Neztic83** [comment]
Alright, I've tried it. Issue 1. doesn't seem to be fixed on my end, here's the output:
![Screenshot_6](https://github.com/user-attachments/assets/72d74631-28e1-40c4-8eb2-d6ebeff8601f)
![Screenshot_7](https://github.com/user-attachments/assets/a2b25911-8004-44e6-b027-16d32299d277)
It loops this endlessly.
[Error Log.txt](https://github.com/user-attachments/files/18307892/Error.Log.txt)

I think 2. may be fixed, but it's hard to say currently.

Skipping 3. because you already said it's not working yet.

4. is fixed.

There were also a few issues I've encountered before in the last version, but forgot to mention them, and one has carried over to this version.

6. Fails to find certain movies
During the past few days, I've been going through the movies, through #, and a quarter through A before the update came out.
Here and there, there have been a few that just fail to even start downloading:
![error1](https://github.com/user-attachments/assets/94a086d0-0b9e-407b-b953-4ddcb0339130)
![error2](https://github.com/user-attachments/assets/60ac330b-6f58-439b-8d19-35ec4dfa791c)

Because of the distance I covered, and how I logged movies that didn't download into a txt, here's what all didn't download:

#:
10 Lives (2024) (7+)
200% Wolf

A:
A Mystery On The Cattle Hill Express

This has carried over to the current version.

7. When downloading at the lowest possible quality, some may download at a higher quality at times
This has happened to me in an older version that would let me download more than three episodes, occasionally during a series, it would download one at a higher quality than others. It is fixable from the user's perspective, just redownload a few times and you get the correct quality. It hasn't been a problem for me as I've been downloading at the highest possible quality.

Just because I'm listing all these problems doesn't mean I hate it or anything, in fact, I thought of some suggestions overtime. Well, one is a suggestion, and the other's more like an idea.

1. A way to queue multiple downloads at once.
A way to download multiple movies or series back to back would be convenient.

2. Support for other, similar websites, potentially
I'm not specifically referring to other cartoon/anime sites like this one, but rather other download sites that are easy to get into.
I have a specific example in mind; [https://musify.club/artist/](url) 

This was a site I discovered via a catalog of various free content provides (which I shall not name, don't want it being taken down). It's like WCO, but for music. All of the song mp3s are just out there for download, and despite the lack of coverage of this site, the library is shockingly vast, (with a way to look at everything too, which is nice) to the point where it'd take years to get through it all. Other music websites on the catalog are nowhere near as large, and are mainly just current, popular songs only.

My idea is that you can link an artist or album, and then it would open a window with the list of available (because some are not) songs, like the download confirm window.

I have a little bit of experience programming, but none at all with getting website data. I'd assume that it would take a while to rework the code to work with multiple websites, so perhaps this could be a separate program instead? It's just an idea I had while thinking away, let me know what you think about that. 

I don't know if there's a place to just put in suggestions or not, so I'm just jotting it down here. I apologize if there was.

**Comment by Neztic83** [comment]
I accidentally clicked "Close with comment", whoops. I'm still new to all of this, haha.

**Comment by Neztic83** [comment]
I accidentally clicked "Close with comment", whoops. I'm still new to this, haha.

**Comment by NobilityDeviant** [comment]
> Alright, I've tried it. Issue 1. doesn't seem to be fixed on my end, here's the output: ![Screenshot_6](https://private-user-images.githubusercontent.com/193023270/400159195-72d74631-28e1-40c4-8eb2-d6ebeff8601f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMzIxMTQsIm5iZiI6MTczNjAzMTgxNCwicGF0aCI6Ii8xOTMwMjMyNzAvNDAwMTU5MTk1LTcyZDc0NjMxLTI4ZTEtNDBjNC04ZWIyLWQ2ZWJlZmY4NjAxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQyMzAzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzVlYWFhOGM3Nzg4OThjMTNjYzg4NTVmN2ZkYmQxNTI2MTMyMmNkMTRmNTljMmY2NDE0YjYyOTUyMGE4ZDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Z6RWxlFR-1iZH0ZnBWunDBgAowwN1aRHPv6heXSbNiM) ![Screenshot_7](https://private-user-images.githubusercontent.com/193023270/400159389-a2b25911-8004-44e6-b027-16d32299d277.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMzIxMTQsIm5iZiI6MTczNjAzMTgxNCwicGF0aCI6Ii8xOTMwMjMyNzAvNDAwMTU5Mzg5LWEyYjI1OTExLTgwMDQtNDRlNi1iMDI3LTE2ZDMyMjk5ZDI3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQyMzAzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTc1NTAwOTEyNDJjNWVlN2I4NzdiMGExYWYyZGQ1NzA3OWE5NDEwOTU5NjJhYWI0ZGIxZDYzNDkwNTkwNTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vAwkDmiGpQBt4VbxyEWRy5YNrorhvEOGP4hEtul8NqI) It loops this endlessly. [Error Log.txt](https://github.com/user-attachments/files/18307892/Error.Log.txt)
> 
> I think 2. may be fixed, but it's hard to say currently.
> 
> Skipping 3. because you already said it's not working yet.
> 
> 4. is fixed.
> 
> There were also a few issues I've encountered before in the last version, but forgot to mention them, and one has carried over to this version.
> 
> 6. Fails to find certain movies
>    During the past few days, I've been going through the movies, through #, and a quarter through A before the update came out.
>    Here and there, there have been a few that just fail to even start downloading:
>    ![error1](https://private-user-images.githubusercontent.com/193023270/400159639-94a086d0-0b9e-407b-b953-4ddcb0339130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMzIxMTQsIm5iZiI6MTczNjAzMTgxNCwicGF0aCI6Ii8xOTMwMjMyNzAvNDAwMTU5NjM5LTk0YTA4NmQwLTBiOWUtNDA3Yi1iOTUzLTRkZGNiMDMzOTEzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQyMzAzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGU4ZGY1OGZhNDE4N2RmOThlODY4MWYxZWQ1N2M5YmQ4MDYwZTBmZjY0ZTAzMTFhY2M4NjI4NmJiYTA0OGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TK6Z3wVsTLFGr_FSVpAacZ80hGnHXE0t2UwmUP2iKa8)
>    ![error2](https://private-user-images.githubusercontent.com/193023270/400159642-60ac330b-6f58-439b-8d19-35ec4dfa791c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMzIxMTQsIm5iZiI6MTczNjAzMTgxNCwicGF0aCI6Ii8xOTMwMjMyNzAvNDAwMTU5NjQyLTYwYWMzMzBiLTZmNTgtNDM5Yi04ZDE5LTM1ZWM0ZGZhNzkxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNFQyMzAzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjQ1OTYxM2NkMzM1MTJmOThkYWM0NWU2N2E3MzY0YzBkNzRkNDkyZDJhMjZkZmUwMTU4M2RlYTg4MDA1MmIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mX7I9XI7HhN6LEM5fHK9EGcg0ot4_nrb497P5Y0f37A)
> 
> Because of the distance I covered, and how I logged movies that didn't download into a txt, here's what all didn't download:
> 
> #: 10 Lives (2024) (7+) 200% Wolf
> 
> A: A Mystery On The Cattle Hill Express
> 
> This has carried over to the current version.
> 
> 7. When downloading at the lowest possible quality, some may download at a higher quality at times
>    This has happened to me in an older version that would let me download more than three episodes, occasionally during a series, it would download one at a higher quality than others. It is fixable from the user's perspective, just redownload a few times and you get the correct quality. It hasn't been a problem for me as I've been downloading at the highest possible quality.
> 
> Just because I'm listing all these problems doesn't mean I hate it or anything, in fact, I thought of some suggestions overtime. Well, one is a suggestion, and the other's more like an idea.
> 
> 1. A way to queue multiple downloads at once.
>    A way to download multiple movies or series back to back would be convenient.
> 2. Support for other, similar websites, potentially
>    I'm not specifically referring to other cartoon/anime sites like this one, but rather other download sites that are easy to get into.
>    I have a specific example in mind; [https://musify.club/artist/](url)
> 
> This was a site I discovered via a catalog of various free content provides (which I shall not name, don't want it being taken down). It's like WCO, but for music. All of the song mp3s are just out there for download, and despite the lack of coverage of this site, the library is shockingly vast, (with a way to look at everything too, which is nice) to the point where it'd take years to get through it all. Other music websites on the catalog are nowhere near as large, and are mainly just current, popular songs only.
> 
> My idea is that you can link an artist or album, and then it would open a window with the list of available (because some are not) songs, like the download confirm window. Artists have duplicate songs with the same titles, but are re-recordings. They could be auto numbered by the program.
> 
> I have a little bit of experience programming, but none at all with getting website data. I'd assume that it would take a while to rework the code to work with multiple websites, so perhaps this could be a separate program instead? It's just an idea I had while thinking away, let me know what you think about that.
> 
> I don't know if there's a place to just put in suggestions or not, so I'm just jotting it down here. I apologize if there was.

Thank you again for the report
Any queue issues weren't resolved because I barely encounter them myself, so it's hard to reproduce.
Even when I download the reported episodes, I rarely see an error.
That's why I updated the error logging & consoles which seemed to have worked thankfully.
It must be episode/series specific or it could be an internet/host issue as well. 
I believe I know a way to tackle this universally or at least write something more specific to the console if it's out of my control.

The movies are unfortunately just a bonus that could potentially cease to exist at any moment.
Not every single movie listed is publicly available through my "free download method" and they are pretty low priority. I'll check any movies you submit, however it's most likely going to be out of my control.

I have also noticed this issue with quality sometimes. See if it can't find a certain quality, it defaults to the next one it finds which i believe prioritizes higher quality. Luckily it still downloads, but I'll look into this quality issue.
My quality discovery code can be improved, but it's also potentially out of my control.
I have tested the quality over and over with countless videos and the result is usually always consistently confusing. 
It's either the page isn't fully loading, the server refuses to show the quality links or i'm over looking something.
I hope the latter is the case. I will see if I find any new discoveries.

As for the suggestions

`A way to queue multiple downloads at once.`

There is a way to queue multiple downloads at once. If the downloader is currently running and you try to download something else, it'll just add it to the queue.

`A way to download multiple movies or series back to back would be convenient.`

Movies work the same as any other video with not much limits besides maybe their single page in DownloadConfirm.  Like i said, you can add anything extra to the queue if it's downloading.

If anything it's an issue with the queue itself. Something is killing the download loop task and that will be my next priority. You say this didn't happen in the old version and I haven't actually compared them yet.
It has to be something i'm missing and i'll dig deep for the next update.

And finally for the music suggestion

That is a great idea and I'm sure it wouldn't be too hard, but that would be very low priority until everything else is fixed. I appreciate the idea and enthusiasm, though as a one man team, it's pretty tough to even fix the issues sometimes. I do love it, but I can't work on this all the time.  

This update was only part 1. This is why I pushed this one so early in order to potentially collect as many issues as possible so report all you can if you want. It will take awhile due to me not having much time, but it will get done eventually.

Thanks again

**Comment by Neztic83** [comment]
I've read through this before but never got back. I remembered about what you said about the download queue a bit ago and decided to try it. It doesn't seem to work, the start button isn't clickable while a download is active and when I hit enter with a link in the bar, I get this message:

![Screenshot_8](https://github.com/user-attachments/assets/8fdce7c2-03ea-4861-b59a-3b577e80c6c5)

**Comment by Neztic83** [comment]
I just found out why downloading from a series eventually fails after a few episodes. 

When I have the default video download set to 576p, the download queue will go through just fine and the whole series will download if other problems don't get in the way. But if I run it with 1080p quality, it will always fail after downloading three episodes, every single time.

**Comment by Neztic83** [comment]
I just found out why downloading from a series eventually fails after a few episodes. 

When I have the default video download set to 576p, the download queue will go through just fine and the whole series will download if other problems don't get in the way. But if I run it with 1080p quality, it will always fail after downloading three episodes, every single time.

Error console output:

[console.txt](https://github.com/user-attachments/files/18512495/console.txt)

**Comment by NobilityDeviant** [comment]
> I've read through this before but never got back. I remembered about what you said about the download queue a bit ago and decided to try it. It doesn't seem to work, the start button isn't clickable while a download is active and when I hit enter with a link in the bar, I get this message:
> 
> ![Screenshot_8](https://github.com/user-attachments/assets/8fdce7c2-03ea-4861-b59a-3b577e80c6c5)
> 
> And about the other easy to dig into websites suggestion, yeah that should be a very very low priority. I found out a few days ago that for Musify, I can just use an extension like DownThemAll on every page of a song list opened as tabs (because they're divided into multiple pages). I let it go on as I sleep now. That's what happens with me though, I'm always thinking up these new aspects for a project, and often times it results in my own becoming too much for me. But still, even if you are just one person who can't work on this all the time, your work is very commendable. I often have existential thoughts about like, what if I was in a bunker in the middle of the desert, with no other form of civilization. Just me, a phone, a solar charger, and many external harddrives worth of content. I'm just happy this exists and you're able to give it some upkeep here and there. I'm incredibly thankful this exists through and through.

Ohh i forgot to remove that. Since the downloader always open the video database, you need to add the queues through the database. I had that check since the very start of the program and I will remove it.
Thank you for the kind words. I had to take a break for awhile, but this program is always in the back of my mind.
I think I will start restructuring the program for other website support this year. Wco can't last forever and it has it's issues which doesn't give me much hope for the future. I will need to figure out some way to add custom scripts or something. 

To top that off I will need to add: Pause support, new thread support (when you start with one thread and queue more, it still only uses the 1 initial thread.), module support etc etc
I will experiment on that in my free time. I am going to try and make this more community driven which will hopefully pull in some more users. We'll see what happens.

**Comment by NobilityDeviant** [comment]
> I just found out why downloading from a series eventually fails after a few episodes.
> 
> When I have the default video download set to 576p, the download queue will go through just fine and the whole series will download if other problems don't get in the way. But if I run it with 1080p quality, it will always fail after downloading three episodes, every single time.
> 
> Error console output:
> 
> [console.txt](https://github.com/user-attachments/files/18512495/console.txt)

Ok that's good info. I never use 1080p and I will test that out. Timeout errors seem to be consistent too which doesn't even mean that it's an internet issue. I think there is a hang inside the quality searching which i've seen a lot before.
I'll be looking into it. 👍

Also as a side note, try using some other website to upload texts such as: [https://pastejustit.com/?utm_source=pastebin.ai&utm_medium=organic](https://pastejustit.com/?utm_source=pastebin.ai&utm_medium=organic)

It's not really a big deal, but it would be easier.

**Comment by NobilityDeviant** [comment]
> I just found out why downloading from a series eventually fails after a few episodes.
> 
> When I have the default video download set to 576p, the download queue will go through just fine and the whole series will download if other problems don't get in the way. But if I run it with 1080p quality, it will always fail after downloading three episodes, every single time.
> 
> Error console output:
> 
> [console.txt](https://github.com/user-attachments/files/18512495/console.txt)

Alright I know the quality is the issue, but no matter what I try it doesn't trigger for me.
I'm going to need a little more info from you if you don't mind.

Please give me:

- Your timeout option value
- Your internet speed ([https://www.speedtest.net](https://www.speedtest.net))
- What series or specific episodes you're trying to download

**Comment by Neztic83** [comment]
Network timeout is at the default (30), my internet download speed is roughly 7.27 according to the listed site, and I was downloading from 101 Dalmatians: The Series at the time of dumping the log to txt.

I've tried 1.0.8, and the issue seems to have fixed itself. However, it will eventually break when downloading a sequence of episodes greater than 9 or 10 or more (it's inconsistent). It will sometimes show messages that it needs to retry in the log, but spam the error console with a lot of stuff, adding more and more to it each minute in delay. I've never recorded a video before until now, but I recorded a video showing what happens. Impatiently waiting for it to upload on Youtube.. I'll make an extra comment once it uploads.

Image of it mumbling in the log (After doing this, it will break and not write anymore logs. But it won't stop the downloading process, making me have to manually stop it)): 

![Image](https://github.com/user-attachments/assets/e0b1fac6-a9bf-4ea9-b5a0-daaba77236ad)

There have also been occasions where when downloading at 570p default quality, there is an uncommon chance for it to download at a higher quality (always 720p) later down the road during a queue (often 20 or more videos in, and always only one, while future videos are 570p as far as I've tried). To keep it consistent, I have to stop it's download process and start it again at that video, then it redownloads the video at the consistent quality. There is no log or console info regarding why this happens. This is untested with 1.0.8.

**Comment by Neztic83** [comment]
Alright, it's uploaded: https://youtu.be/HfNbTdSJkn8

I did copy the console output, but forgot about that third seemingly unique output it gave. Simply didn't cross my mind.
Either way, here's that:
[console.txt](https://github.com/user-attachments/files/18549439/console.txt)

**Comment by NobilityDeviant** [comment]
So everything goes smooth, then it throws an error and it completely stops downloading.
A script error for when it finds resolutions... and maybe a couple of different errors in that region.
Ok that's very helpful, I'll look into right now. There should be failsafes for this type of stuff. I have no clue why that's not working. The higher quality issue is also very odd, assuming your default resolution option is at 576p, there should be no reason for it to download at a higher quality since there's always a 576p option.
I will report back with my findings. Thank you again.

**Comment by NobilityDeviant** [comment]
Ok i added a couple of changes to quality searching which seems to be the main issue you're facing.
[1.0.81](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.81)

However I do suggest setting your timeout option to 60 or even higher due to your internet speed.

**Comment by Neztic83** [comment]
I've tried the new update, and I've set my timeout option to 70 just incase. I haven't tested the quality issue yet, but while downloading at 1080p by default, on rare occasions it does download at the lowest possible quality, again with no error console or log as to why. Redownloading the episode fixes this. I have been experimenting with the max amount of videos before the downloader breaks, and 10 videos per queue seems to be the safest max number.

I have also discovered another issue; when attempting to download from https://www.wcofun.net/anime/2-43-seiin-koukou-danshi-volley-bu-english-subbed , selecting an episode causes an error message to display: 

![Image](https://github.com/user-attachments/assets/ee1d1922-3edf-427f-8d15-d593dcfe8e51)

It will then cause the downloader window to crash when OK is pressed. Pressing Start again causes the program itself to crash, with another error appearing: 

![Image](https://github.com/user-attachments/assets/b5ebeb15-b167-4793-a3a9-3a5950e532ad)

Once you click OK, this window appears:

![Image](https://github.com/user-attachments/assets/9120272e-f7e1-415e-99b3-551a628ab6e4)

After clicking OK for the last time, the program closes. It does not cause any errors and I can reopen the program again. Opening that URL again with the downloader causes the same result everytime.

**Comment by Neztic83** [comment]
Alright, I've just turned my computer back on and freshly reinstalled without opening the program prior. Still broke, same errors.

**Comment by NobilityDeviant** [comment]
> I've tried the new update, and I've set my timeout option to 70 just incase. I haven't tested the quality issue yet, but while downloading at 1080p by default, on rare occasions it does download at the lowest possible quality, again with no error console or log as to why. Redownloading the episode fixes this. I have been experimenting with the max amount of videos before the downloader breaks, and 10 videos per queue seems to be the safest max number.
> 
> I have also discovered another issue; when attempting to download from https://www.wcofun.net/anime/2-43-seiin-koukou-danshi-volley-bu-english-subbed , selecting an episode causes an error message to display:
> 
> ![Image](https://github.com/user-attachments/assets/ee1d1922-3edf-427f-8d15-d593dcfe8e51)
> 
> It will then cause the downloader window to crash when OK is pressed. Pressing Start again causes the program itself to crash, with another error appearing:
> 
> ![Image](https://github.com/user-attachments/assets/b5ebeb15-b167-4793-a3a9-3a5950e532ad)
> 
> Once you click OK, this window appears:
> 
> ![Image](https://github.com/user-attachments/assets/9120272e-f7e1-415e-99b3-551a628ab6e4)
> 
> After clicking OK for the last time, the program closes. It does not cause any irreversable errors and I can reopen the program again. Opening that URL again with the downloader causes the same result everytime. There are no error console messages about this.
> 
> EDIT: Nevermind, it does break the program. Reopening the program and downloader with a different series causes the same events to happen, making me have to reinstall.
> 
> EDIT 2: It actually seems to mess up something with the zen database folder, making me have to redownload it. It messes up your download history and causes the program to crash when you visit it.
> 
> EDIT 3: Nevermind, the entire program is broken now. Redownloading your database folder makes the history no longer crash, but now selecting any episode causes the same error windows to appear, so now I can't use it. I have freshly installed multiple times but to no avail. I am absolutely positive that 2.43: Seiin Koukou Danshi Volley-bu English Subbed is what caused this to happen, though, as I was going through every series from top to bottom and it didn't happen previously. The next time I shut my laptop off and get back on, I'll freshly install and try it one last time to make sure, and will jot down what happens.

I've noticed this as well and I did fix the issue. Certain new episodes were causing it and I wasn't catching the errors properly. It's not a cache issue it's purely an image issue. I'm not done with the update, but I will push it to address such a critical error in a bit.

**Comment by NobilityDeviant** [comment]
Also I believe I have addressed the quality issue officially.
Certain qualities weren't loading properly from the site, so I added a new way to loop and retry quality checking.
Unfortunately that quality error rarely ever gets thrown for me, so I can't test the new javascript error function, but I'm sure it should work.

**Comment by NobilityDeviant** [comment]
Ok it's been released in [1.0.82](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.82)

**Comment by Neztic83** [comment]
I've tried it, but it still seems to be happening. Crashes afterwords. Is there some kind of log file where I can get the full text?

![Image](https://github.com/user-attachments/assets/01be590a-f85d-4dc6-a58d-d07551d077ed)

**Comment by NobilityDeviant** [comment]
I rushed the other fix but the new one in [1.0.83](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.83) should address this crash.

**Comment by NobilityDeviant** [comment]
Ok thank you for everything but im going to close this now. The program has changed a lot since this report and I feel like it's not longer a valid issue. It has helped a lot though.
