### ISSUE TITLE
CDP Version Error

### ISSUE THREAD

**Issue by TheJester343** [NobilityDeviant/ZenDownloader#5]
Hello, I am trying to use this downloader and every time I go to download something it is giving me " Retrying... Failed to determine file size" and failing to download anything. the log error I am receiving is 

Aug 30, 2024 12:18:52 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 128, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 128

I have updated and checked everything i can think of, i have updated Selenium, Crome, C++ studio, my PC itself, i checked Java, Python.

but I finally got it to work kinda, it'll go for a little bit but then stop.

This is the Debug message I am receiving.

[3:35]   (Session info: chrome=128.0.6613.86)
[3:35] Build info: version: '4.23.1', revision: '656257d8e9'
[3:35] System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
[3:35] Driver info: nobility.downloader.core.driver.undetected_chrome.UndetectedChromeDriver
[3:35] Command: [317a736d15d1862e806f3e38e410dda6, findElement {value=cizgi-js-0, using=id}]
[3:35] Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.86, chrome: {chromedriverVersion: 128.0.6613.86 (3045ed680fda...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: 127.0.0.1:64097}, pageLoadStrategy: normal, platformName: any, proxy: Proxy(), se:cdp: ws://127.0.0.1:64097/devtoo..., se:cdpVersion: 128.0.6613.86, setWindowRect: false, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
[3:35] Session ID: 317a736d15d1862e806f3e38e410dda6
[3:35] [BaseContinuationImpl] [E] Failed to find flag cizgi-video-js-0. Trying next one.
[3:36] Error: timeout: Timed out receiving message from renderer: 30.000

This is the Error Console logs i am getting,

at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
Stacktrace for Failed to find flag cizgi-js-0 for demon-slayer-episode-8-english-dubbed. Trying next one.
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: 30.000
(Session info: chrome=128.0.6613.86)
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.11'
Driver info: nobility.downloader.core.driver.undetected_chrome.UndetectedChromeDriver
Command: [6336545f92235b29156944fbb1c12f1b, executeScript {args=[], script=
window.goToThis = function(url) {
var link = document.createElement("a");
link.setAttribute("href", url);
link.style.display = "none";
document.body.appendChild(link);
link.click();
}
goToThis('https://embed.watchanimesub.net/inc/embed/video-js.php?file=animes%2FWatch%20Kimetsu%20no%20Yaiba%20%28Dub%29%20Episode%208.flv&hd=1&pid=472712&h=816bce860e4da754e80f2601601cf84b&t=1725057381&embed=ndisk');
}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 128.0.6613.86, chrome: {chromedriverVersion: 128.0.6613.86 (3045ed680fda...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: 127.0.0.1:64098}, pageLoadStrategy: normal, platformName: any, proxy: Proxy(), se:cdp: ws://127.0.0.1:64098/devtoo..., se:cdpVersion: 128.0.6613.86, setWindowRect: false, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6336545f92235b29156944fbb1c12f1b
at jdk.internal.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:476)
at nobility.downloader.core.driver.DriverBase.executeJs(DriverBase.kt:121)
at nobility.downloader.core.scraper.VideoDownloader.detectAvailableResolutions(VideoDownloader.kt:429)
at nobility.downloader.core.scraper.VideoDownloader.access$detectAvailableResolutions(VideoDownloader.kt:29)
at nobility.downloader.core.scraper.VideoDownloader$run$2.invokeSuspend(VideoDownloader.kt:79)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
Stacktrace for Failed to find flag cizgi-video-js-0 for demon-slayer-episode-8-english-dubbed. Trying next one.
org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: cizgi-video-js-0 (tried for 10 second(s) with 1000 milliseconds interval)
Build info: version: '4.23.1', revision: '656257d8e9'

If you have any advice it will be greatly accepted,

P.S.
I am a python Guy so I recognize some of the errors so I was able to get it to the point its at but I don't want to brick it.
If I'm missing something, obvious just call me stupid.

Thank You!

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by NobilityDeviant** [comment]
This does seem to happen sometimes. it looks like it's failing on the javascript section that I use.
Let me see if it's happening globally

**Comment by NobilityDeviant** [comment]
Ok I want to clarify that the cdp mismatch is practically inevitable. Selenium can't keep up with Chrome constantly updating in Seleniums stable version and I don't want to have to keep updating to any other version besides stable. That is not the issue in this case and most likely never will be.

This might to be an internet issue on your end.

Have you tried increasing the timeout? What's your internet speed?

I have successfully downloaded what you're trying to download with no issues.

**Comment by NobilityDeviant** [comment]
Btw ignore Krissv2 if they ever comment something. That was immediately flagged as a virus lol

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by TheJester343** [comment]
Ok Got it,

After you talked about speed, yes that's probably the issue,

where I live the speed isn't that great.
![Speed](https://github.com/user-attachments/assets/c7c25b92-466b-4f61-8600-6a4d091a7f25)


Thank you

**Comment by NobilityDeviant** [comment]
> Ok Got it,
> 
> After you talked about speed, yes that's probably the issue,
> 
> where I live the speed isn't that great. ![Speed](https://private-user-images.githubusercontent.com/152147736/363426457-c7c25b92-466b-4f61-8600-6a4d091a7f25.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjY5ODUsIm5iZiI6MTcyNTEyNjY4NSwicGF0aCI6Ii8xNTIxNDc3MzYvMzYzNDI2NDU3LWM3YzI1YjkyLTQ2NmItNGY2MS04NjAwLTZhNGQwOTFhN2YyNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNzUxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2YwN2Y5YjQyZGJhYzYyODI5NWY5MDQ5OTIxYWYxNWMyMjY5ODY5MTVkZDFkYzg3ODk5NTA4ZTRmY2U0ZDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A_iHp732dl7WBm0LbmVyVFsDsOXsQM8q6nR6I1dMWd4)
> 
> Thank you

that is pretty fast actually.
i'll look into it at slower speeds and see if I can improve anything. I know the file size issue does have a bit of problems I should be able to fix.

**Comment by TheJester343** [comment]
> > Ok Got it,
> > After you talked about speed, yes that's probably the issue,
> > where I live the speed isn't that great. ![Speed](https://private-user-images.githubusercontent.com/152147736/363426457-c7c25b92-466b-4f61-8600-6a4d091a7f25.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMjY5ODUsIm5iZiI6MTcyNTEyNjY4NSwicGF0aCI6Ii8xNTIxNDc3MzYvMzYzNDI2NDU3LWM3YzI1YjkyLTQ2NmItNGY2MS04NjAwLTZhNGQwOTFhN2YyNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNzUxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2YwN2Y5YjQyZGJhYzYyODI5NWY5MDQ5OTIxYWYxNWMyMjY5ODY5MTVkZDFkYzg3ODk5NTA4ZTRmY2U0ZDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A_iHp732dl7WBm0LbmVyVFsDsOXsQM8q6nR6I1dMWd4)
> > Thank you
> 
> that is pretty fast actually. I'll look into it at slower speeds and see if I can improve anything. I know the file size issue does have a bit of problems I should be able to fix.

Ok ill work with what I got right now, if you manage to find a fix ill be looking for that update, 

If I run into any other issues ill let you know,

and the other thing I don't use Crome, So I downloaded and am using the Crome form the Driver website you posted in the readme, would this have any affect on what I might be dealing with?
[](https://googlechromelabs.github.io/chrome-for-testing/#stable)

thank you.

**Comment by NobilityDeviant** [comment]
Sorry i've been a little busy lately.

I believe I have fixed this in: [Commit](https://github.com/NobilityDeviant/ZenDownloader/commit/03e4c28864aeeb9e00fb39cfbce8e1c4ca69d2f1)

I will push the update most likely tomorrow after a couple more tweaks and tests. 👍

**Comment by NobilityDeviant** [comment]
Update has been pushed.

Let me know if it helped at all!

[Release](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.4)

**Comment by TheJester343** [comment]
When i try downloading with the new update it times out pretty quick,

[0:58] Successfully launched video downloader for 25 episode(s).
[0:59] [I] Using chrome browser from settings.
[0:59] Chrome Browser Path: C:\Program Files\Google\chrome-win64\chrome.exe
[0:59] Chrome Driver Path: C:\Program Files\Google\chromedriver-win64\chromedriver.exe
[0:59] [I] Scraping resolution links from https://wcofun.net/blue-exorcist-episode-1-english-dubbed-2 in simple mode.
[0:59] [I] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.
[0:59] Failed in simple mode. Retrying with 1/5 left.
[0:59] [I] Scraping resolution links from https://wcofun.net/blue-exorcist-episode-1-english-dubbed-2 in simple mode.
[0:59] [I] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.
[0:59] Failed in simple mode. Retrying with 2/5 left.
[0:59] [I] Scraping resolution links from https://wcofun.net/blue-exorcist-episode-1-english-dubbed-2 in simple mode.
[0:59] [I] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.
[0:59] Failed in simple mode. Retrying with 3/5 left.
[0:59] [I] Scraping resolution links from https://wcofun.net/blue-exorcist-episode-1-english-dubbed-2 in simple mode.
[0:59] [I] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.
[0:59] Failed in simple mode. Retrying with 4/5 left.
[0:59] [I] Scraping resolution links from https://wcofun.net/blue-exorcist-episode-1-english-dubbed-2 in simple mode.
[0:59] [I] Using UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.
[0:59] Failed in simple mode. Retrying with 5/5 left.
[0:59] Reached max simple mode retries for Blue Exorcist Episode 1 English Dubbed Turning it off.
[0:59] Gracefully finished. No downloads have been made.



Sep 07, 2024 12:59:25 PM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 128, returning the closest version; found: 127; Please update to a Selenium version that supports CDP version 128
Sep 07, 2024 12:59:32 PM org.openqa.selenium.remote.http.WebSocket$Listener onError
WARNING: Connection reset
java.net.SocketException: Connection reset
at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube.readAvailable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(Unknown Source)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
                


I have tried with a VPN and without, this is all I get,

i have also tried doing this at on one of my friends PC's so see if location and internet speed was a possible issue but i get the same error (as shown above)

i have also tried it on a fresh install windows system and I am getting the same thing.

any insight?



also here are the speeds of my friends place

![Capture](https://github.com/user-attachments/assets/807dc027-7af9-433f-bee2-e9f74c693d2e)

**Comment by NobilityDeviant** [comment]
Oh no i left something in there from testing. It's not supposed to stop after a failure immediately it's supposed to use the regular way.

Have you tried other animes? That one in particular is using a different video player which isn't supported atm.

Let me push a little update to fix my mistake and i'll look into that video player in a bit.

**Comment by NobilityDeviant** [comment]
Ok i fixed the simple mode issue in: [1.0.41](https://github.com/NobilityDeviant/ZenDownloader/releases/tag/1.0.41)

I'm marking this as closed as it's getting too long and i'm opening a new one for those video players.
